version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: B34tG3n3r4t0r
      MYSQL_DATABASE: BeatsDB
      MYSQL_USER: application
      MYSQL_PASSWORD: B34tG3n3r4t0r
      MYSQL_ROOT_HOST: localhost
    ports:
      - "3306:3306"
    volumes:
      - C:/dev/mysql_data:/var/lib/mysql
      - C:/dev/mysql_config:/etc/mysql/conf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mysql_network

volumes:
  mysql_data:
  mysql_config:

networks:
  mysql_network:
    driver: bridge