-- init.sql
-- CREATE USER 'root'@'%' IDENTIFIED BY 'root';
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS `BeatsDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `TestDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'application'@'%' IDENTIFIED BY 'application';
GRANT ALL PRIVILEGES ON *.* TO 'application'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;